/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [id]
      ,[email]
      ,[password]
      ,[q1]
      ,[q2]
      ,[q3]
      ,[q4]
      ,[q5]
      ,[q6]
      ,[q7]
      ,[q8]
      ,[q9]
      ,[q10]
  FROM [User_data].[dbo].[users]